version: '3.9'
networks:
  laravel:

services:
  app:
    build: .
    container_name: laravel_scaffold
    command: >-
      sh -c "
        apk add php8-pecl-xdebug && composer install ;\
        cp .docker/php.ini-development /etc/php8/php.ini ;\
        cp .docker/xdebug.ini /etc/php8/conf.d/50_xdebug.ini ;\
        php artisan serve --host 0.0.0.0 --port 80"
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html:rw
    networks:
      - app_network

      
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:pro
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - laravel


  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4036:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE : homestead
      MYSQL_USER : homestead
      MYSQL_PASSWORD : secret
      MYSQL_ROOT_PASSWORD : secret
      SERVICE_TAGS : dev
      SERVICE_NAME : mysql
    networks:
      - laravel


  php:
    image: php:8-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD : secret
    networks:
      - laravel

