version: '3.9'
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginxx
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:pro
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - laravel


  mysql:
    image: mysql:latest
    container_name: mysqli
    restart: unless-stopped
    tty: true
    ports:
      - "4037:3307"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE : ahmad
      MYSQL_USER : homestead
      MYSQL_PASSWORD : secret
      MYSQL_ROOT_PASSWORD : secret
      SERVICE_TAGS : dev
      SERVICE_NAME : mysql
    networks:
      - laravel


  php:
    image: php:8-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpp
    volumes:
      - ./src:/var/www/html
    ports:
      - "9090:9090"
    networks:
      - laravel


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadminn
    depends_on:
      - mysql
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD : secret
    networks:
      - laravel

